server:
  port: 8281
  profile: release

log:
  level: info
  file: /home/echils/Downloads/golang.log
  
mysql:
  url: tcp(localhost:3306)/workspace?charset=utf8mb4&parseTime=true
  username: root 
  password: 123456

redis:
  host: localhost
  port: 6379

minio:
  host: 172.31.249.3
  port: 48903
  username: root
  password: v@aseit.0N9B
