server:
  name: golang
  port: 8080
  profile: release

log:
  level: 5
  file: /log
  
mysql:
  url: tcp(localhost:3306)/workspace?charset=utf8mb4&parseTime=true
  username: root 
  password: 123456

redis:
  host: localhost
  port: 6379

