server:
  port: 8281
  
mysql:
  url: tcp(localhost:3306)/workspace?charset=utf8mb4&parseTime=True&loc=Local"
  username: root 
  password: 123456

redis:
  host: localhost
  port: 6379

minio:
  host: 172.31.249.3
  port: 48103
  username: root
  password: v@aseit.0N9B
