server:
  name: golearn
  port: 8081
  mode: release

log:
  dir: /log
  level: 5
 
mysql:
  url: tcp(127.0.0.1:3306)/workspace?charset=utf8mb4&parseTime=True&loc=Local
  username: root
  password: 123456

redis:
  host: 127.0.0.1
  port: 6379
  